### ISSUE TITLE
test/dev secrets in secrets.yml

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/roadrunner-rails#22]
/config/[secrets.yml](https://github.com/department-of-veterans-affairs/roadrunner-rails/blob/setup-script/config/secrets.yml) has a secret_key_base in the file for both test and development.  The production one is moved to an environment variable, test/dev are not. 

I am assuming this is intended and as desired, but wanted to bring it up just in case it wasn't.  If this is intended, please close this issue. If it's not intended, should we move those to environment variables?

**Comment by emilyville** [comment]
Should be reclassified/renamed (for now) to add content into the guide to document the process as is.

**Comment by awong-dev** [comment]
@ayaleloehr Is this still right to have in this sprint? If not, please move to backlog.

**Comment by ayaleloehr** [comment]
Reading on the internet, the way we have this seems like a pretty common and secure practice.  No changes needed. Closing.
