### ISSUE TITLE
Figure out suggested Puma configuration

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/roadrunner-rails#23]
[This](https://github.com/18F/college-choice/issues/597#issuecomment-139034834) thread suggests we use 5 threads per worker and 3 workers per instance.  I assume we'll also need to run it with a `-e production` flag, or to set that somewhere.  We should settle on a configuration and probably put it in `/config/puma.rb`

**Comment by plusjeff** [comment]
Created a ticket for this in vets.gov-ops. Closing this one.
