### ISSUE TITLE
Add automated accessibility testing

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/roadrunner-rails#3]
We're using Pa11y on Caseflow, by loading up a couple views and running the scanner on them in a [shell script](https://github.com/department-of-veterans-affairs/caseflow/blob/master/.travis/pa11y.sh).

What I'd like to do is incorporate this check in between every step of every Capybara feature test. This way we'll scan (hopefully) every state the application can be in.

There's a gem that currently does this, [CapybaraAccessible](https://github.com/Casecommons/capybara-accessible/tree/master/lib/capybara/accessible) but it's a little rusty (last commit in 2014).

It also uses [Google Chrome Accessibility Tools](https://github.com/GoogleChrome/accessibility-developer-tools) instead of pa11y. Not sure which one is better... does anyone have any thoughts?

We could create a gem (or outsource a gem to 18f) for this? After scanning the source of CapybaraAccessible, it doesn't seem like it'd be too difficult.

**Comment by plusjeff** [comment]
https://github.com/benbalter/ra11y

**Comment by plusjeff** [comment]
Reached out to Alan deLevie at 18F who had been working on Rspec integration for Ra11y. We're going to chat next week.

**Comment by shanear** [comment]
I'd love to chat too. I looked at Pa11y, and it doesn't seem like a good fit. It has a dependency on npm, which causes friction. That'd be fine if we needed it, but I dug through the source and it's just a shim for HTML CodeSniffer, which they vendor (and we can vendor too).

Also, the big goal i'd like to achieve with this is effortless accessibility coverage. We can do this with a Capybara plugin that scans the page after every step of feature tests.

What do you think?

**Comment by shanear** [comment]
Alright, so I put together a little gem that injects the code sniffer in between actions:

https://github.com/department-of-veterans-affairs/sniffybara

It's rough, but the gets the job done right now, and I can def polish the gem (yeah. i'm rolling with that metaphor :smile:) if we decide to go this direction.

You can see it working in action here:

https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/13

**Comment by shanear** [comment]
Also, I'm noticing there are some issues with HTML Code Sniffer Section 508 mode, so going with WCAG 2.0 for the time being.

this is unsettling:
https://github.com/squizlabs/HTML_CodeSniffer/issues/153
