### ISSUE TITLE
Should rake commands have bundle exec?

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/roadrunner-rails#32]
Was reading [this article](http://stackoverflow.com/questions/8275885/use-bundle-exec-rake-or-just-rake) and it sounds like we should be using `bundle exec` before `rake` commands.  The readme for this repo says to run `rake lint`, `rake ci`, and `rake security`.  Should we change these all to add `bundle exec` in front of them?

**Comment by shanear** [comment]
yeah, if you have a bunch of different projects with different versions of gems installed on your machine, you'll need to run bundle exec.

My experience is that most of the time it's unnecessary and I find typing `bundle exec` annoying. But i agree, we should document the bundle exec version. I'll get on that.
