### ISSUE TITLE
Make it easy to download a clean project (for starting a new project)

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/roadrunner-rails#4]
Use Raygun for generating new projects:
https://github.com/carbonfive/raygun-rails

In addition to changing all the names, it may also need to:
- delete example files
- modify the README.md to not be Roadrunner Rails

**Comment by plusjeff** [comment]
Read through all the Raygun code. This is all it does:

1. Copy down a GitHub repo
1. Do a find/replace on string variations of "App Template" (like "app-template", "AppTemplate" etc.)

I think we can successfully replicate the perks of Raygun (easy starting a project), without actually using Raygun. Instead, we can just keep the project clean and have folks download the ZIP file from the Road Runner guide.

**Comment by shanear** [comment]
I agree. I'm also ok with the startup script doing what Raygun does. Just thought it might be easy to ride of their stuff.
