### ISSUE TITLE
Add startup file

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/roadrunner-rails#8]

**Comment by paultag** [comment]
Is this an init script?

If so, what platform are we deploying to -- we'll have to pick either system or upstart. I'd say systemd, and that'll match with modern Debian, Ubuntu and RHEL, but upstart is still used on legacy Ubuntu and RHEL

**Comment by plusjeff** [comment]
Nope - sorry for the lack of detail!

@shanear - Can you refresh my memory on this. I remember being a `./bin/....` file in the project, but don't remember it's purpose.

**Comment by plusjeff** [comment]
Ah - remembered what this is.

There'd be a `./bin/setup` script that would do all the initial application configuration, saving a developer from having to do it manually.
